# Generated by Django 5.0.3 on 2024-06-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(choices=[('teacher', "O'qituvchi"), ('admin', 'Admin'), ('superuser', 'Superadmin')], default='teacher', max_length=200, verbose_name='Xodim statusi'),
        ),
    ]
