# Generated by Django 5.0.1 on 2024-04-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile-pictures/user-default.png', null=True, upload_to='profile-pictures/', verbose_name='Profil rasmi'),
        ),
    ]
