# Generated by Django 5.0.3 on 2024-04-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_alter_user_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, choices=[("O'qituvchi", "O'qituvchi"), ('Admin', 'Admin'), ('Superadmin', 'Superadmin')], default="O'qituvchi", max_length=200, null=True, verbose_name='Xodim statusi'),
        ),
    ]
