# Generated by Django 4.2.6 on 2023-11-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_alter_user_options_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(default="O'qituvchi", max_length=200),
        ),
    ]
