# Generated by Django 5.0.3 on 2024-04-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_alter_user_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, choices=[('teacher', "O'qituvchi"), ('admin', 'Admin'), ('superuser', 'Superadmin')], default='teacher', max_length=200, null=True, verbose_name='Xodim statusi'),
        ),
    ]
