# Generated by Django 4.2.6 on 2023-11-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_user_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, default="O'qituvchi", max_length=200, null=True),
        ),
    ]
