# Generated by Django 5.0.1 on 2024-04-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_alter_user_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(choices=[('teacher', "O'qituvchi"), ('admin', 'Admin'), ('superuser', 'Superadmin')], default='teacher', max_length=200, verbose_name='Xodim statusi'),
        ),
    ]
