# Generated by Django 4.2.6 on 2024-01-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0007_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=200, unique=True, verbose_name="E-mail manzil"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile-pictures/user-default.png",
                null=True,
                upload_to="thedevu101-admin-media/profile-pictures/",
                verbose_name="Profil rasmi",
            ),
        ),
    ]
