# Generated by Django 4.2.6 on 2024-02-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0009_smssentcount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smssentcount",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
