# Generated by Django 4.2.6 on 2024-02-08 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0010_alter_smssentcount_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="smssentcount",
            options={
                "verbose_name": "SMS soni ",
                "verbose_name_plural": "Yuborilgan SMS lar soni",
            },
        ),
        migrations.AlterField(
            model_name="smssentcount",
            name="teacher",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
