# Generated by Django 4.2.6 on 2023-10-21 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchisi"),
        ),
        migrations.AlterUniqueTogether(
            name='pupil',
            unique_together={('first_name', 'last_name', 'group')},
        ),
    ]
