# Generated by Django 4.2.6 on 2023-10-20 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Fan nomi'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Guruh nomi')),
                ('price', models.IntegerField(default=0, verbose_name="Guruh to'lovi")),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_main.subject', verbose_name='Fan nomi')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchisi")),
            ],
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('first_name', models.CharField(max_length=200, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=200, verbose_name='Familiya')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_main.group')),
            ],
            options={
                'unique_together': {('first_name', 'last_name', 'group')},
            },
        ),
    ]
