# Generated by Django 4.2.6 on 2023-10-25 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_main', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('owner_fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('month', models.CharField(max_length=200, null=True, verbose_name='To\\lov oyi')),
                ('pupil_fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('group_name', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.IntegerField(verbose_name="To'lov")),
                ('note', models.TextField(verbose_name="Eslatma / To'lov tarifi")),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name="To'lov vaqti")),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan vaqt")),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_main.group', verbose_name='Guruh')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pupil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_main.pupil', verbose_name="O'quvchi")),
            ],
        ),
    ]
