# Generated by Django 4.2.6 on 2023-10-26 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.DateField(max_length=200, null=True, verbose_name="To'lov oyi"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name="Eslatma / To'lov tarifi"),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_main.group', verbose_name='Guruh'),
        ),
    ]
