# Generated by Django 4.2.6 on 2023-10-31 23:44

import app_main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_alter_payment_month_alter_payment_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='price',
            field=models.IntegerField(validators=[app_main.validators.min_value_validator], verbose_name="Guruh to'lovi"),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[app_main.validators.subject_name_length_validator], verbose_name='Fan nomi'),
        ),
    ]
