# Generated by Django 4.2.6 on 2024-01-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0006_alter_payment_options_expense"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
