# Generated by Django 4.2.6 on 2024-02-07 17:03

import app_main.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_main", "0007_expense_note"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ["name", "created"]},
        ),
        migrations.AddField(
            model_name="pupil",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[app_main.validators.expense_amount_validator],
                verbose_name="Miqdor (so'mda)",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nima uchun"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="note",
            field=models.TextField(
                blank=True, null=True, verbose_name="Qo'shimcha ma'lumot"
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="O'qituvchi",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="owner_fullname",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="O'qituvchi"
            ),
        ),
    ]
